version: "3.2"
services:
  apir:
    build:
      context: ./apir
      dockerfile: dev.Dockerfile
    container_name: dime_apir
    working_dir: /var/apir
    volumes:
      - ./apir:/var/apir
      - ${SEMAPHORE_CACHE_DIR}/bundle:/bundle
    depends_on:
        - mysql
    env_file: 'apir/.env.semaphore'
  mysql:
    image: mysql:5.7
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    container_name: dime_db
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
    - ./database:/var/lib/mysql
  frontend:
    image: node:12
    container_name: dime_web-client
    volumes:
    - ./frontend:/var/frontend
    working_dir: /var/frontend
